// The capability matrix (docs/mode-matrix.md), generated from supports(): which features work in which document
// depth and colour mode. `mode_matrix` prints it; `mode_matrix --write <file>` writes it; `mode_matrix --check <file>`
// fails when the committed file differs from what supports() says now (a ctest test), so the doc cannot drift.
#include <algorithm>
#include "compositor/supports.h"
#include <cstring>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

using namespace compositor;

namespace {

struct Column { const char* name; SampleType type; ColorMode mode; };
constexpr Column columns[] = {
    {"RGB8", SampleType::U8, ColorMode::RGB},    {"RGB16", SampleType::U16, ColorMode::RGB}, {"RGB32", SampleType::F32, ColorMode::RGB},
    {"CMYK8", SampleType::U8, ColorMode::CMYK},  {"CMYK16", SampleType::U16, ColorMode::CMYK},
    {"Lab8", SampleType::U8, ColorMode::Lab},    {"Lab16", SampleType::U16, ColorMode::Lab},
};

std::string escape(std::string_view text) {
    std::string out;
    for (char c : text) {
        if (c == '|') out += "\\|";
        else out += c;
    }
    return out;
}

std::string matrix() {
    std::ostringstream o;
    o << "# Capability matrix\n\n"
      << "<!-- Generated by tests/mode_matrix.cpp from supports() (src/core/src/supports.cpp); do not edit by hand.\n"
      << "     Regenerate: build/tests/mode_matrix --write docs/mode-matrix.md (ctest's mode_matrix_check fails when it is stale). -->\n\n"
      << "What works in a document of each depth and colour mode, as the menus, tools and automation gate it "
      << "([bit-depth.md](bit-depth.md), [color-modes.md](color-modes.md)). CMYK and Lab exist at 8 and 16 bits only, as in "
      << "Photoshop.\n\n"
      << "- **native**: works on the document's own samples.\n"
      << "- **native\\*** : works, but some of its pixels are made in RGB and converted (the note says which).\n"
      << "- **greyed (Photoshop lacks)**: Photoshop has no such feature in that mode or depth; greyed for good "
      << "(\"Not available in 32-bit mode\", \"Not available in CMYK mode\").\n"
      << "- **greyed (not yet)**: waiting for a port (\"... yet\").\n\n"
      << "| Feature | id |";
    for (const Column& c : columns) o << " " << c.name << " |";
    o << " Notes |\n|---|---|";
    for (size_t i = 0; i < sizeof(columns) / sizeof(columns[0]); i++) o << "---|";
    o << "---|\n";
    size_t count = 0;
    const FeatureRow* rows = featureRows(count);
    for (size_t r = 0; r < count; r++) {
        const FeatureRow& row = rows[r];
        o << "| " << escape(row.label) << " | `" << escape(row.feature) << "` |";
        // Each note once, after the columns it applies to.
        std::vector<std::pair<std::string, std::string>> notes;   // note, columns
        auto addNote = [&](std::string_view note, const char* column) {
            for (auto& n : notes) if (n.first == note) { n.second += std::string(", ") + column; return; }
            notes.push_back({std::string(note), column});
        };
        for (const Column& c : columns) {
            const std::string why = unavailableReason(row.feature, c.type, c.mode);
            if (!why.empty() && row.feature == "brush.mypaint" && c.mode != ColorMode::RGB)
                addNote("libmypaint mixes RGB only; greyed rather than painting through RGB and back", c.name);
            if (why.empty()) {
                const std::string_view note = throughRgbNote(row.feature, c.type, c.mode);
                if (note.empty()) o << " native |";
                else {
                    o << " native\\* |";
                    addNote(note, c.name);
                }
            } else if (why.size() >= 4 && why.compare(why.size() - 4, 4, " yet") == 0) {
                o << " greyed (not yet) |";
            } else {
                o << " greyed (Photoshop lacks) |";
            }
        }
        std::string text;
        for (const auto& n : notes) text += (text.empty() ? "" : "; ") + n.second + ": " + n.first;
        o << " " << escape(text) << " |\n";
    }
    o << "\nA feature id missing from the tables is 8-bit RGB only (supports.h): new features are safe by default.\n";
    return o.str();
}

} // namespace

int main(int argc, char** argv) {
    const std::string text = matrix();
    if (argc == 3 && std::strcmp(argv[1], "--write") == 0) {
        std::ofstream out(argv[2], std::ios::binary);
        out << text;
        return out ? 0 : 1;
    }
    if (argc == 3 && std::strcmp(argv[1], "--check") == 0) {
        std::ifstream in(argv[2], std::ios::binary);
        std::stringstream held;
        held << in.rdbuf();
        // Line endings aside (a Windows checkout may turn them into CRLF).
        std::string committed = held.str();
        committed.erase(std::remove(committed.begin(), committed.end(), '\r'), committed.end());
        if (committed == text) return 0;
        std::cerr << argv[2] << " is stale: regenerate it with mode_matrix --write " << argv[2] << "\n";
        std::istringstream a(committed), b(text);
        std::string la, lb;
        for (int line = 1;; line++) {
            const bool moreA = bool(std::getline(a, la)), moreB = bool(std::getline(b, lb));
            if (!moreA && !moreB) break;
            if (!moreA) la.clear();
            if (!moreB) lb.clear();
            if (la != lb) { std::cerr << "  first difference, line " << line << ":\n  committed: " << la << "\n  generated: " << lb << "\n"; break; }
        }
        return 1;
    }
    std::cout << text;
    return 0;
}
